"""sentinel_engine.strategies._supertrend_ref — VENDORED FROZEN COPY.

Source: `D:/WebDev/TOKATA/mt5/scripts/supertrend_ref.py` (TOKATA's validated
reference implementation, read-only). Vendored 2026-07-10 for the EMASAR V1
MT5-fidelity integration (design spec
docs/superpowers/specs/2026-07-10-emasar-v1-mt5-integration-design.md,
Component 5) so SENTINEL stays self-contained on Win10/11 with no
cross-project import at runtime.

DO NOT EDIT this file to "fix" or "improve" it — it is a byte-for-byte
mirror (module docstring/comments untranslated, kept as-is for diffability
against the source) of the TOKATA-validated math. If the vendored copy needs
to change, re-vendor from the TOKATA source and re-run the golden test in
`tests/strategies/test_emasar_ref.py`.
"""
"""Referencia canonica del SuperTrend (recursion estandar) para paridad con el EA.
trend[i] = +1 alcista (linea=finalLower), -1 bajista (linea=finalUpper)."""

def supertrend(highs, lows, closes, atr, mult):
    n = len(closes)
    fin_up = [0.0]*n
    fin_lo = [0.0]*n
    trend  = [0]*n
    line   = [0.0]*n
    for i in range(n):
        hl2 = (highs[i] + lows[i]) / 2.0
        b_up = hl2 + mult*atr[i]
        b_lo = hl2 - mult*atr[i]
        if i == 0:
            fin_up[i] = b_up
            fin_lo[i] = b_lo
            trend[i]  = +1 if closes[i] >= hl2 else -1
        else:
            fin_up[i] = b_up if (b_up < fin_up[i-1] or closes[i-1] > fin_up[i-1]) else fin_up[i-1]
            fin_lo[i] = b_lo if (b_lo > fin_lo[i-1] or closes[i-1] < fin_lo[i-1]) else fin_lo[i-1]
            if trend[i-1] == +1 and closes[i] < fin_lo[i]:
                trend[i] = -1
            elif trend[i-1] == -1 and closes[i] > fin_up[i]:
                trend[i] = +1
            else:
                trend[i] = trend[i-1]
        line[i] = fin_lo[i] if trend[i] == +1 else fin_up[i]
    return trend, line


def flips(trend):
    out = []
    for i in range(1, len(trend)):
        if trend[i] != trend[i-1]:
            out.append((i, trend[i]))
    return out
