"""sentinel_engine.strategies.emasar_ref — VENDORED FROZEN COPY.

Source: `D:/WebDev/TOKATA/mt5/scripts/emasar_ref.py` (TOKATA's validated
reference implementation, read-only). Vendored 2026-07-10 for the EMASAR V1
MT5-fidelity integration (design spec
docs/superpowers/specs/2026-07-10-emasar-v1-mt5-integration-design.md,
Component 5) so SENTINEL stays self-contained on Win10/11 with no
cross-project import at runtime, while inheriting the validated math.

DO NOT EDIT this file to "fix" or "improve" it — it is a mirror of the
TOKATA-validated reference (module docstrings/comments untranslated, kept
as-is for diffability against the source). If the vendored copy needs to
change, re-vendor from the TOKATA source and re-run the golden test in
`tests/strategies/test_emasar_ref.py`. The ONLY intentional deviation from
the source is the `supertrend_ref` import below, changed from TOKATA's
top-level `mt5/scripts/` module layout to this package's vendored
`_supertrend_ref` sibling (see that file's own provenance header) — no
other line was altered.

SENTINEL's own `sentinel_engine/strategies/emasar.py` (the V2-only
`EmasarPolicy` used by `sim/lite.py`) is UNTOUCHED by this vendoring — that
remains the existing sim-engine path; this module only ANNOTATES/VERIFIES
imported MT5 V1 positions (see `sentinel_engine/research/ingest_mt5_deals.py`).
"""
from ._supertrend_ref import supertrend as _supertrend_batch


# ---------- helpers puros ----------
def _sma_maybe(vals, n):
    """SMA de ventana n; None si algun elemento de la ventana es None o falta historia."""
    out = [None] * len(vals)
    for i in range(len(vals)):
        if i < n - 1:
            continue
        ventana = vals[i - n + 1:i + 1]
        if any(v is None for v in ventana):
            continue
        out[i] = sum(ventana) / n
    return out


# ---------- indicadores ----------
def ema_series(closes, period):
    """EMA estandar: semilla SMA(period) en la primera ventana completa, recursion despues.
    None mientras no hay historia suficiente (paridad con iMA modo EMA de MT5)."""
    n = len(closes)
    out = [None] * n
    if n < period:
        return out
    k = 2.0 / (period + 1)
    seed = sum(closes[0:period]) / period
    out[period - 1] = seed
    for i in range(period, n):
        out[i] = closes[i] * k + out[i - 1] * (1 - k)
    return out


def sar_series(highs, lows, step, max_step):
    """Parabolic SAR estandar (recursion Wilder), identica a stac_ref.sar_series.
    trend[i]: +1 = SAR bajo el precio (alcista), -1 = SAR sobre el precio (bajista)."""
    n = len(highs)
    if n == 0:
        return [], []
    sar = [None] * n
    trend = [0] * n
    up = True if n < 2 else highs[1] >= highs[0]
    ep = highs[0] if up else lows[0]
    af = step
    sar[0] = lows[0] if up else highs[0]
    trend[0] = +1 if up else -1
    for i in range(1, n):
        cur = sar[i - 1] + af * (ep - sar[i - 1])
        if up:
            techo = min(lows[i - 1], lows[i - 2]) if i >= 2 else lows[i - 1]
            cur = min(cur, techo)
            if lows[i] < cur:
                up = False
                cur = ep
                ep = lows[i]
                af = step
            elif highs[i] > ep:
                ep = highs[i]
                af = min(af + step, max_step)
        else:
            piso = max(highs[i - 1], highs[i - 2]) if i >= 2 else highs[i - 1]
            cur = max(cur, piso)
            if highs[i] > cur:
                up = True
                cur = ep
                ep = highs[i]
                af = step
            elif lows[i] < ep:
                ep = lows[i]
                af = min(af + step, max_step)
        sar[i] = cur
        trend[i] = +1 if up else -1
    return sar, trend


def ao_series(highs, lows):
    """AO = SMA(mediana,5) - SMA(mediana,34), mediana=(H+L)/2 (spec S2)."""
    median = [(highs[i] + lows[i]) / 2.0 for i in range(len(highs))]
    sma5 = _sma_maybe(median, 5)
    sma34 = _sma_maybe(median, 34)
    return [None if (sma5[i] is None or sma34[i] is None) else sma5[i] - sma34[i]
            for i in range(len(median))]


def ac_series(highs, lows):
    """AC = AO - SMA(AO,5) (spec S2)."""
    ao = ao_series(highs, lows)
    ao_sma5 = _sma_maybe(ao, 5)
    return [None if (ao[i] is None or ao_sma5[i] is None) else ao[i] - ao_sma5[i]
            for i in range(len(ao))]


def momentum_series(closes, period):
    """Momentum estandar MT5: 100 * close[i] / close[i-period]. None sin historia suficiente."""
    n = len(closes)
    out = [None] * n
    for i in range(period, n):
        out[i] = 100.0 * closes[i] / closes[i - period]
    return out


# ---------- ConfirmMode (S2) ----------
def oscilador_favorable(osc, i, mode, direccion):
    """osc[i]=valor en indice [1] del spec, osc[i-1]=[2], osc[i-2]=[3]. direccion:
    +1 = favorable a LONG, -1 = favorable a SHORT. mode: 1=creciente, 2=acelerando.
    Requiere historia suficiente (None -> no favorable)."""
    if i < 1 or osc[i] is None or osc[i - 1] is None:
        return False
    if mode == 1:
        return (osc[i] > osc[i - 1]) if direccion == +1 else (osc[i] < osc[i - 1])
    if mode == 2:
        if i < 2 or osc[i - 2] is None:
            return False
        d1 = osc[i] - osc[i - 1]
        d2 = osc[i - 1] - osc[i - 2]
        return (d1 > d2) if direccion == +1 else (d1 < d2)
    raise ValueError(f"ConfirmMode invalido: {mode}")


def g5_confirmacion(ao, ac, mom, i, mode, direccion, *, confirm_count=2, ac_mag_threshold=0.0):
    """G5: >=confirm_count de 3 osciladores {AO, Momentum, AC} favorables segun ConfirmMode
    (spec S1/S2 Fase 0; ConfirmCount y AC_MagThreshold: spec Fase 1 S1). confirm_count=2
    (Fase 0, default) o 3 (exige los 3). ac_mag_threshold>0 anade a G5 la exigencia de
    magnitud minima de aceleracion: |AC[i]-AC[i-1]| > ac_mag_threshold."""
    votos = sum([
        oscilador_favorable(ao, i, mode, direccion),
        oscilador_favorable(mom, i, mode, direccion),
        oscilador_favorable(ac, i, mode, direccion),
    ])
    if votos < confirm_count:
        return False
    if ac_mag_threshold > 0.0:
        if i < 1 or ac[i] is None or ac[i - 1] is None:
            return False
        if abs(ac[i] - ac[i - 1]) <= ac_mag_threshold:
            return False
    return True


# ---------- Engulfing (S4) ----------
def bearish_engulfing(o1, c1, o2, c2):
    """Cierre de LONG: [1] bajista, [2] alcista, cuerpo de [1] engulle al de [2]."""
    return (c1 < o1) and (c2 > o2) and (o1 >= c2) and (c1 <= o2)


def bullish_engulfing(o1, c1, o2, c2):
    """Cierre de SHORT (espejo): [1] alcista, [2] bajista, cuerpo de [1] engulle al de [2]."""
    return (c1 > o1) and (c2 < o2) and (o1 <= c2) and (c1 >= o2)


# ---------- Gate compuesto de entrada (S1) ----------
def gate_long(bars, ema8, ema20, ema5, sar_trend, ao, ac, mom, i, *, confirm_mode, use_ema5,
              confirm_count=2, ac_mag_threshold=0.0, skip_g3=False, require_ema_order=True):
    """Evalua G1..G5 para LONG en indice i (>=2 de historia). use_ema5: True para V2 (G3
    usa EMA5), False para V1 (G3 usa EMA8). Devuelve (True/False, detalle dict de gates).
    confirm_count/ac_mag_threshold: extensiones Fase 1 (defaults preservan Fase 0). skip_g3
    (EntryTiming=1): omite G3 (el toque intrabar lo reemplaza en el llamador, spec Fase1 S1).
    require_ema_order (correccion trader 2026-07-09): True (default, Fase 0) exige G1
    (EMA8>EMA20). False lo omite del AND: basta con que ambas EMAs vayan en la MISMA
    orientacion (G2) sin importar cual esta sobre cual -> mas entradas."""
    if i < 2:
        return False, {}
    e8, e8p = ema8[i], ema8[i - 1]
    e20, e20p = ema20[i], ema20[i - 1]
    if None in (e8, e8p, e20, e20p) or sar_trend[i] is None:
        return False, {}
    g1 = e8 > e20
    slope8 = e8 - e8p
    slope20 = e20 - e20p
    # G2: cruzadas (signos opuestos de pendiente) -> no opera en ningun lado.
    cruzadas = (slope8 > 0 and slope20 < 0) or (slope8 < 0 and slope20 > 0)
    g2 = (slope8 > 0 and slope20 > 0) and not cruzadas
    ema_pull = ema5[i] if use_ema5 else ema8[i]
    if ema_pull is None:
        return False, {}
    if skip_g3:
        g3 = True
    else:
        bar1 = bars[i]
        g3 = (bar1["low"] < ema_pull) and (bar1["close"] > bar1["open"])
    g4 = sar_trend[i] == +1
    g5 = g5_confirmacion(ao, ac, mom, i, confirm_mode, +1,
                          confirm_count=confirm_count, ac_mag_threshold=ac_mag_threshold)
    detalle = dict(g1=g1, g2=g2, g3=g3, g4=g4, g5=g5)
    g1_efectivo = g1 if require_ema_order else True
    return (g1_efectivo and g2 and g3 and g4 and g5), detalle


def gate_short(bars, ema8, ema20, ema5, sar_trend, ao, ac, mom, i, *, confirm_mode, use_ema5,
               confirm_count=2, ac_mag_threshold=0.0, skip_g3=False, require_ema_order=True):
    """Espejo exacto de gate_long (S1.1). require_ema_order: ver gate_long."""
    if i < 2:
        return False, {}
    e8, e8p = ema8[i], ema8[i - 1]
    e20, e20p = ema20[i], ema20[i - 1]
    if None in (e8, e8p, e20, e20p) or sar_trend[i] is None:
        return False, {}
    g1 = e8 < e20
    slope8 = e8 - e8p
    slope20 = e20 - e20p
    cruzadas = (slope8 > 0 and slope20 < 0) or (slope8 < 0 and slope20 > 0)
    g2 = (slope8 < 0 and slope20 < 0) and not cruzadas
    ema_pull = ema5[i] if use_ema5 else ema8[i]
    if ema_pull is None:
        return False, {}
    if skip_g3:
        g3 = True
    else:
        bar1 = bars[i]
        g3 = (bar1["high"] > ema_pull) and (bar1["close"] < bar1["open"])
    g4 = sar_trend[i] == -1
    g5 = g5_confirmacion(ao, ac, mom, i, confirm_mode, -1,
                          confirm_count=confirm_count, ac_mag_threshold=ac_mag_threshold)
    detalle = dict(g1=g1, g2=g2, g3=g3, g4=g4, g5=g5)
    g1_efectivo = g1 if require_ema_order else True
    return (g1_efectivo and g2 and g3 and g4 and g5), detalle


# ---------- pip / defaults ----------
def pip_size(symbol, pipsize_input=0.0):
    """S3.3: PipSize=0 -> auto por simbolo. XAUUSD=0.01, NQ100=1.0 (punto indice)."""
    if pipsize_input:
        return pipsize_input
    if symbol.upper().startswith("XAU"):
        return 0.01
    return 1.0


# ---------- gestion de posicion (S3) ----------
class _Ficha:
    __slots__ = ("lado", "entry", "sl", "max_fav", "abierta", "es_runner", "stall_consec")

    def __init__(self, lado, entry, sl, es_runner=False):
        self.lado = lado          # +1 long, -1 short
        self.entry = entry
        self.sl = sl
        self.max_fav = entry      # maximo (long) / minimo (short) precio favorable visto
        self.abierta = True
        self.es_runner = es_runner  # F3: marca si esta ficha es la "conviction runner" (Fase 1)
        self.stall_consec = 0     # runner_exit_mode='stall': velas consecutivas sin nuevo maximo


def _toque_long(bars, ema_pull, i):
    """EntryTiming=1 (S1 Fase 1): aproximacion Model=1. La barra base [i] es la misma que en
    modo cierre dispara la entrada (G1/G2/G4/G5 se satisfacen con datos de [i], el EMA/SAR/
    osciladores ya calculados con el historial hasta [i]; no hay look-ahead porque estos
    indicadores usan cierres <= i, disponibles en cuanto la barra abre). La diferencia vs
    cierre es SOLO el momento y precio de entrada: en touch se entra en cuanto low[i]<=EMA[i]
    (el toque intrabar, sin esperar el cierre de [i]), a precio = nivel EMA tocado."""
    if ema_pull[i] is None:
        return False, None
    nivel = ema_pull[i]
    if bars[i]["low"] <= nivel:
        return True, nivel
    return False, None


def _toque_short(bars, ema_pull, i):
    if ema_pull[i] is None:
        return False, None
    nivel = ema_pull[i]
    if bars[i]["high"] >= nivel:
        return True, nivel
    return False, None


def ac_desacelerando(ac, idx, direccion):
    """AC_ExitEnable/AC_ModulateTrail (spec Fase1 S1): AC[i]<AC[i-1] (long) / AC[i]>AC[i-1]
    (short) -> la aceleracion se apaga. direccion: +1 long, -1 short."""
    if idx < 1 or ac[idx] is None or ac[idx - 1] is None:
        return False
    return (ac[idx] < ac[idx - 1]) if direccion == +1 else (ac[idx] > ac[idx - 1])


def centro_masa(bar):
    """Centro de masa de una vela: (O+H+L+C)/4 (spec runner-momentum, caso 20:37 2026-07-07)."""
    return (bar["open"] + bar["high"] + bar["low"] + bar["close"]) / 4.0


def momentum_slope_agota(bars, i, direccion, *, min_consecutivas=2):
    """Alternativa A (runner-momentum): pendiente entre centros de masa de velas cerradas
    consecutivas. Dispara cuando hay >= min_consecutivas pendientes seguidas desfavorables
    (<=0 para LONG, >=0 para SHORT) terminando en [i]. Requiere i-min_consecutivas >= 0."""
    if i - min_consecutivas < 0:
        return False
    for k in range(i - min_consecutivas + 1, i + 1):
        slope = centro_masa(bars[k]) - centro_masa(bars[k - 1])
        favorable_o_neutro = (slope > 0) if direccion == +1 else (slope < 0)
        if favorable_o_neutro:
            return False
    return True


def momentum_stall_step(bar, extremo_prev, direccion, consec_prev):
    """Alternativa B (runner-momentum), paso incremental por barra: compara el extremo
    favorable (high para LONG / low para SHORT) de [i] contra el extremo acumulado previo.
    Si mejora, resetea el contador de velas-sin-nuevo-maximo a 0; si no, lo incrementa.
    Devuelve (nuevo_extremo, nuevo_consec)."""
    val = bar["high"] if direccion == +1 else bar["low"]
    mejora = (val > extremo_prev) if direccion == +1 else (val < extremo_prev)
    if mejora:
        return val, 0
    return extremo_prev, consec_prev + 1


def ac_fuerte(ac, idx, direccion):
    """AC_ConvictionRunner (solo V1, spec Fase1 S1): (AC[1]-AC[2]) > (AC[2]-AC[3]) con margen
    para LONG (espejo invertido para SHORT) -> aceleracion creciente clara."""
    if idx < 2 or ac[idx] is None or ac[idx - 1] is None or ac[idx - 2] is None:
        return False
    d1 = ac[idx] - ac[idx - 1]
    d2 = ac[idx - 1] - ac[idx - 2]
    return (d1 > d2) if direccion == +1 else (d1 < d2)


def simular(bars, *, strategy_mode=1, confirm_mode=1, symbol="XAUUSD", pipsize_input=0.0,
            ema_fast=8, ema_slow=20, ema_pull=5, sar_step=0.02, sar_max=0.20,
            st_atr_period=10, st_mult=3.0, mom_period=14, init_sl_pips=3.0, trail_pips=170.0,
            allow_long=True, allow_short=True,
            entry_timing=0, confirm_count=2, ac_exit_enable=False,
            ac_conviction_runner=False, ac_mag_threshold=0.0, ac_modulate_trail=False,
            v2_use_trail=False, runner_exit_mode="baseline",
            runner_slope_min_consecutivas=2, runner_stall_k=3,
            require_ema_order=True, init_sl_mode="pips", init_sl_range_k=1.0,
            trail_mode="pips", trail_range_k=1.0):
    """Simula el EA sobre una serie OHLC cronologica del TF base. Devuelve lista de eventos
    [{'idx', 'lado':'L'|'S', 'precio', 'motivo', 'ficha':'F1'|'F2'|'F3'|None}].
    motivo in {ENTRY_L, ENTRY_S, EXIT_ENGULF, EXIT_STFLIP, EXIT_TRAIL, EXIT_INITSL, EXIT_ACDECEL,
    EXIT_MOMSLOPE, EXIT_MOMSTALL}.
    Extensiones Fase 1 (spec 2026-07-08 fase1 S1), defaults preservan Fase 0:
    entry_timing (0=cierre, 1=toque intrabar aproximado), confirm_count (2 o 3),
    ac_exit_enable (cierra ficha si AC desacelera), ac_conviction_runner (F3 solo si
    aceleracion fuerte, solo V1), ac_mag_threshold (magnitud minima en G5),
    ac_modulate_trail (aprieta trailing a Trail_Pips/2 al apagarse AC),
    v2_use_trail (V2: trailing + catastrofe ademas de engulfing).
    runner_exit_mode (caso 20:37 2026-07-07, F3 unicamente; 'baseline' default preserva
    EXACTAMENTE el trailing Fase 0): 'slope' reemplaza el trailing de F3 por la Alternativa A
    (pendiente de centros de masa: cierra cuando >= runner_slope_min_consecutivas velas
    seguidas tienen pendiente desfavorable/neutra, solo tras un nuevo maximo a favor desde la
    entrada -> EXIT_MOMSLOPE); 'stall' reemplaza el trailing de F3 por la Alternativa B
    (estancamiento: cierra cuando pasan runner_stall_k velas consecutivas sin nuevo
    maximo/minimo favorable -> EXIT_MOMSTALL).
    Correcciones del trader (2026-07-09), defaults preservan Fase 0:
    require_ema_order (True default): False omite G1 (EMA8 sobre/bajo EMA20); basta la
    misma orientacion de pendientes (G2) -> corrige la falta de entradas.
    init_sl_mode ('pips' default | 'range'): 'range' fija el SL inicial como multiplo del
    rango de la vela de senal [i]: LONG sl = low[i] - init_sl_range_k*(high[i]-low[i]);
    SHORT sl = high[i] + init_sl_range_k*(high[i]-low[i]) (referencia a la vela anterior).
    trail_mode ('pips' default | 'range'): 'range' usa como distancia de trailing
    trail_range_k*(rango de la vela actual) en vez de trail_pips*pip."""
    n = len(bars)
    highs = [b["high"] for b in bars]
    lows = [b["low"] for b in bars]
    closes = [b["close"] for b in bars]

    ema8 = ema_series(closes, ema_fast)
    ema20 = ema_series(closes, ema_slow)
    ema5 = ema_series(closes, ema_pull) if strategy_mode == 2 else [None] * n
    _sar_val, sar_trend = sar_series(highs, lows, sar_step, sar_max)
    ao = ao_series(highs, lows)
    ac = ac_series(highs, lows)
    mom = momentum_series(closes, mom_period)
    # SuperTrend (F2, V1 unicamente) necesita su propio ATR (ATRPeriod=10, Wilder).
    atr = _atr_wilder(highs, lows, closes, st_atr_period)
    st_trend, _st_line = _supertrend_batch(highs, lows, closes,
                                            [a if a is not None else 0.0 for a in atr], st_mult)
    st_valido = [atr[i] is not None for i in range(n)]

    pip = pip_size(symbol, pipsize_input)
    init_sl = init_sl_pips * pip
    trail = trail_pips * pip
    use_ema5 = (strategy_mode == 2)
    ema_pull_arr = ema5 if use_ema5 else ema8

    def _sl_inicial(lado, entry, idx):
        """SL inicial segun init_sl_mode. 'pips': entry -/+ init_sl (Fase 0). 'range':
        referencia al rango de la vela de senal [idx] (correccion trader 2026-07-09)."""
        if init_sl_mode == "range":
            rango = bars[idx]["high"] - bars[idx]["low"]
            return (bars[idx]["low"] - init_sl_range_k * rango) if lado == +1 \
                else (bars[idx]["high"] + init_sl_range_k * rango)
        return (entry - init_sl) if lado == +1 else (entry + init_sl)

    eventos = []
    fichas = {}  # 'F1'/'F2'/'F3' -> _Ficha (V1) o 'F1' unica (V2)

    for i in range(n):
        bar = bars[i]
        px = bar["close"]

        # ---- 1) evaluar salidas de fichas abiertas ----
        for tag in list(fichas.keys()):
            f = fichas[tag]
            if not f.abierta:
                continue
            lado_txt = "L" if f.lado == +1 else "S"

            # SL inicial (V1 siempre; V2 solo si V2_UseTrail con InitSL_Pips>0 = catastrofe).
            sl_activo = (strategy_mode == 1) or (strategy_mode == 2 and v2_use_trail and init_sl_pips > 0)
            if sl_activo:
                if f.lado == +1 and bar["low"] <= f.sl:
                    f.abierta = False
                    eventos.append({"idx": i, "lado": lado_txt, "precio": f.sl,
                                     "motivo": "EXIT_INITSL", "ficha": tag})
                    continue
                if f.lado == -1 and bar["high"] >= f.sl:
                    f.abierta = False
                    eventos.append({"idx": i, "lado": lado_txt, "precio": f.sl,
                                     "motivo": "EXIT_INITSL", "ficha": tag})
                    continue

            # AC_ExitEnable (Fase1): cierra por desaceleracion antes de evaluar el resto.
            if ac_exit_enable and ac_desacelerando(ac, i, f.lado):
                f.abierta = False
                eventos.append({"idx": i, "lado": lado_txt, "precio": px,
                                 "motivo": "EXIT_ACDECEL", "ficha": tag})
                continue

            # Engulfing (F1 en V1; unica/principal salida en V2).
            engulfe = False
            if i >= 1:
                o1, c1, o2, c2 = bar["open"], bar["close"], bars[i - 1]["open"], bars[i - 1]["close"]
                engulfe = bearish_engulfing(o1, c1, o2, c2) if f.lado == +1 \
                    else bullish_engulfing(o1, c1, o2, c2)
            if engulfe and (strategy_mode == 2 or tag == "F1"):
                f.abierta = False
                eventos.append({"idx": i, "lado": lado_txt, "precio": px,
                                 "motivo": "EXIT_ENGULF", "ficha": tag})
                continue

            if strategy_mode == 1 and tag == "F2":
                # ST break (S3.1): cierra cuando SuperTrend gira contra la ficha.
                if st_valido[i] and st_trend[i] is not None:
                    if (f.lado == +1 and st_trend[i] == -1) or (f.lado == -1 and st_trend[i] == +1):
                        f.abierta = False
                        eventos.append({"idx": i, "lado": lado_txt, "precio": px,
                                         "motivo": "EXIT_STFLIP", "ficha": tag})
                        continue

            trail_activo_f3 = strategy_mode == 1 and tag == "F3" and runner_exit_mode == "baseline"
            trail_activo_v2 = strategy_mode == 2 and tag == "F1" and v2_use_trail and trail_pips > 0
            momentum_activo_f3 = strategy_mode == 1 and tag == "F3" and runner_exit_mode != "baseline"

            if momentum_activo_f3:
                # runner_exit_mode='slope'|'stall' (caso 20:37 2026-07-07): reemplaza el
                # trailing170 de F3 por una salida de momentum. F1/F2 no se tocan.
                hizo_nuevo_max_previo = (f.lado == +1 and f.max_fav > f.entry) or \
                    (f.lado == -1 and f.max_fav < f.entry)
                extremo_actual, f.stall_consec = momentum_stall_step(
                    bar, f.max_fav, f.lado, f.stall_consec)
                f.max_fav = extremo_actual

                disparo = False
                if runner_exit_mode == "slope":
                    disparo = hizo_nuevo_max_previo and momentum_slope_agota(
                        bars, i, f.lado, min_consecutivas=runner_slope_min_consecutivas)
                elif runner_exit_mode == "stall":
                    disparo = hizo_nuevo_max_previo and f.stall_consec >= runner_stall_k
                else:
                    raise ValueError(f"runner_exit_mode invalido: {runner_exit_mode}")

                if disparo:
                    f.abierta = False
                    eventos.append({"idx": i, "lado": lado_txt, "precio": px,
                                     "motivo": "EXIT_MOMSLOPE" if runner_exit_mode == "slope"
                                     else "EXIT_MOMSTALL", "ficha": tag})
                    continue

            if trail_activo_f3 or trail_activo_v2:
                if trail_mode == "range":
                    trail_efectivo = trail_range_k * (bar["high"] - bar["low"])
                else:
                    trail_efectivo = trail
                if ac_modulate_trail and trail_activo_f3 and ac_desacelerando(ac, i, f.lado):
                    trail_efectivo = trail_efectivo / 2.0
                # Trailing: SL = max/min(SL_actual, extremo_desde_entrada -/+ trail_efectivo).
                if f.lado == +1:
                    f.max_fav = max(f.max_fav, bar["high"])
                    nuevo_sl = f.max_fav - trail_efectivo
                    if f.sl is None or nuevo_sl > f.sl:
                        f.sl = nuevo_sl
                else:
                    f.max_fav = min(f.max_fav, bar["low"])
                    nuevo_sl = f.max_fav + trail_efectivo
                    if f.sl is None or nuevo_sl < f.sl:
                        f.sl = nuevo_sl
                if f.lado == +1 and f.sl is not None and bar["low"] <= f.sl:
                    f.abierta = False
                    eventos.append({"idx": i, "lado": lado_txt, "precio": f.sl,
                                     "motivo": "EXIT_TRAIL", "ficha": tag})
                    continue
                if f.lado == -1 and f.sl is not None and bar["high"] >= f.sl:
                    f.abierta = False
                    eventos.append({"idx": i, "lado": lado_txt, "precio": f.sl,
                                     "motivo": "EXIT_TRAIL", "ficha": tag})
                    continue

        fichas = {k: v for k, v in fichas.items() if v.abierta}

        # ---- 2) evaluar entrada (sin fichas abiertas: una entrada por señal, S1) ----
        if fichas:
            continue

        if entry_timing == 1:
            # G3 se reemplaza por el toque intrabar (misma barra [i] que en modo cierre);
            # G1/G2/G4/G5 se evaluan sobre [i] con skip_g3 (spec Fase1 S1, nota de aproximacion).
            long_ok, entry_px_l = _toque_long(bars, ema_pull_arr, i)
            short_ok, entry_px_s = _toque_short(bars, ema_pull_arr, i)
            if long_ok:
                g_rest, _ = gate_long(bars, ema8, ema20, ema5, sar_trend, ao, ac, mom, i,
                                       confirm_mode=confirm_mode, use_ema5=use_ema5,
                                       confirm_count=confirm_count, ac_mag_threshold=ac_mag_threshold,
                                       skip_g3=True, require_ema_order=require_ema_order)
                long_ok = g_rest
            if short_ok:
                g_rest, _ = gate_short(bars, ema8, ema20, ema5, sar_trend, ao, ac, mom, i,
                                        confirm_mode=confirm_mode, use_ema5=use_ema5,
                                        confirm_count=confirm_count, ac_mag_threshold=ac_mag_threshold,
                                        skip_g3=True, require_ema_order=require_ema_order)
                short_ok = g_rest
            px_long = entry_px_l
            px_short = entry_px_s
        else:
            long_ok, _ = gate_long(bars, ema8, ema20, ema5, sar_trend, ao, ac, mom, i,
                                    confirm_mode=confirm_mode, use_ema5=use_ema5,
                                    confirm_count=confirm_count, ac_mag_threshold=ac_mag_threshold,
                                    require_ema_order=require_ema_order)
            short_ok, _ = gate_short(bars, ema8, ema20, ema5, sar_trend, ao, ac, mom, i,
                                      confirm_mode=confirm_mode, use_ema5=use_ema5,
                                      confirm_count=confirm_count, ac_mag_threshold=ac_mag_threshold,
                                      require_ema_order=require_ema_order)
            px_long = px
            px_short = px

        if long_ok and allow_long:
            eventos.append({"idx": i, "lado": "L", "precio": px_long, "motivo": "ENTRY_L", "ficha": None})
            if strategy_mode == 1:
                sl = _sl_inicial(+1, px_long, i)
                runner = True
                if ac_conviction_runner:
                    runner = ac_fuerte(ac, i, +1)
                fichas = {"F1": _Ficha(+1, px_long, sl), "F2": _Ficha(+1, px_long, sl)}
                if runner:
                    fichas["F3"] = _Ficha(+1, px_long, sl, es_runner=True)
            else:
                sl_v2 = _sl_inicial(+1, px_long, i) if (v2_use_trail and init_sl_pips > 0) else None
                fichas = {"F1": _Ficha(+1, px_long, sl_v2)}
        elif short_ok and allow_short:
            eventos.append({"idx": i, "lado": "S", "precio": px_short, "motivo": "ENTRY_S", "ficha": None})
            if strategy_mode == 1:
                sl = _sl_inicial(-1, px_short, i)
                runner = True
                if ac_conviction_runner:
                    runner = ac_fuerte(ac, i, -1)
                fichas = {"F1": _Ficha(-1, px_short, sl), "F2": _Ficha(-1, px_short, sl)}
                if runner:
                    fichas["F3"] = _Ficha(-1, px_short, sl, es_runner=True)
            else:
                sl_v2 = _sl_inicial(-1, px_short, i) if (v2_use_trail and init_sl_pips > 0) else None
                fichas = {"F1": _Ficha(-1, px_short, sl_v2)}

    return eventos


def _atr_wilder(highs, lows, closes, period):
    """ATR Wilder (misma smoothing que iATR de MT5), igual patron que stac_ref.atr_series."""
    n = len(highs)
    tr = [0.0] * n
    atr = [None] * n
    for i in range(n):
        tr[i] = (highs[i] - lows[i]) if i == 0 else max(
            highs[i] - lows[i], abs(highs[i] - closes[i - 1]), abs(lows[i] - closes[i - 1]))
        if i == period - 1:
            atr[i] = sum(tr[:period]) / period
        elif i > period - 1:
            atr[i] = (atr[i - 1] * (period - 1) + tr[i]) / period
    return atr
