"""4.3 — Anchored walk-forward splitter + embargo (Fable Sec. 2.6).

Spec (Fable Sec. 2.6, verbatim intent):
    "Anchored walk-forward as the outer loop: e.g., for 2024-01->2026-06 data,
    folds = train [start, T_i] -> test [T_i, T_i+2 months], stepping 2 months,
    with a 1-day embargo between train and test (purging: any triple-barrier
    label whose horizon crosses the boundary is dropped from train -- Lopez de
    Prado purged K-fold adapted to walk-forward)."

Design (module-scoped ambiguity resolutions, see bottom of file for the log):

  - The anchored train window always starts at the timeline's first
    timestamp and grows fold over fold (never rolls forward).
  - The "1-day embargo between train and test" is materialized by shrinking
    the *usable* train boundary: a fold's usable train region is
    ``[train_start, split - embargo)`` -- i.e. no train sample may fall
    within ``embargo`` of the split point ``T_i``. Test is exactly
    ``[split, split + test_span)``. This gives the adversarial invariant the
    task requires verbatim: no train sample timestamp falls within
    ``[T_i - embargo, T_i + test_span]``.
  - Fold split points are generated by stepping ``T_i = start + k*step`` for
    k = 1, 2, ... while a full test window still fits inside the timeline
    (``split + test_span <= timeline_end``). This yields the first fold as
    soon as one full ``step`` of anchored training data exists, matching the
    "stepping 2 months" language, and guarantees every fold has a complete,
    non-truncated test window.

This module is pure datetime arithmetic -- it does not depend on any other
sentinel_engine.opt module, sentinel_engine.config, or sentinel_engine.engine,
and takes no stance on price data, labels, or the objective. It only exposes
fold boundaries; a labels.purge_labels_at_boundary(...)-style function (Task
4.1) is expected to consume ``Fold.train_end`` / ``Fold.embargo`` to drop any
triple-barrier label whose horizon crosses the boundary.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import Iterable, List, Sequence


@dataclass(frozen=True)
class Fold:
    """One anchored walk-forward fold.

    Attributes:
        index: 0-based fold number (fold order == chronological order).
        train_start: Anchor point -- always the timeline's first timestamp.
        split: T_i, the fold's train/test pivot.
        embargo: The embargo duration applied at this boundary.
        train_end: Exclusive upper bound of the *usable* train region,
            ``split - embargo``. Any sample/label at or after this point
            must not be used for training.
        test_start: Inclusive lower bound of the test region (== split).
        test_end: Exclusive upper bound of the test region
            (== split + test_span).
    """

    index: int
    train_start: datetime
    split: datetime
    embargo: timedelta
    train_end: datetime
    test_start: datetime
    test_end: datetime

    def embargo_start(self) -> datetime:
        """Start of the excluded embargo zone, ``T_i - embargo``."""
        return self.split - self.embargo

    def is_train(self, ts: datetime) -> bool:
        """True if ``ts`` may be used for training under this fold."""
        return self.train_start <= ts < self.train_end

    def is_test(self, ts: datetime) -> bool:
        """True if ``ts`` falls in this fold's test window."""
        return self.test_start <= ts < self.test_end

    def is_embargo(self, ts: datetime) -> bool:
        """True if ``ts`` falls in the excluded embargo zone (neither
        train nor test)."""
        return self.embargo_start() <= ts < self.split

    def train_mask(self, timestamps: Iterable[datetime]) -> List[bool]:
        return [self.is_train(ts) for ts in timestamps]

    def test_mask(self, timestamps: Iterable[datetime]) -> List[bool]:
        return [self.is_test(ts) for ts in timestamps]

    def label_crosses_boundary(self, event_start: datetime, event_end: datetime) -> bool:
        """True if a (triple-barrier) label's event window
        ``[event_start, event_end]`` crosses into the embargo/test region
        of this fold, i.e. it must be purged from train.

        A label is safe for train only if its *entire* horizon
        (open -> resolution) resolves strictly before ``train_end``.
        """
        return event_end >= self.train_end


def anchored_walkforward(
    timeline: Sequence[datetime],
    test_span: timedelta,
    step: timedelta,
    embargo: timedelta = timedelta(days=1),
) -> List[Fold]:
    """Build anchored walk-forward folds over ``timeline``.

    Args:
        timeline: Non-empty sequence of sample timestamps spanning the
            available data range (need not be sorted or evenly spaced;
            only min/max are used to bound fold generation).
        test_span: Length of each fold's test window (e.g. 2 months).
        step: Distance between consecutive split points T_i (e.g. 2 months).
        embargo: Embargo duration subtracted from the train boundary at
            each split (default 1 day per Fable Sec. 2.6).

    Returns:
        Chronologically ordered list of ``Fold``. Empty if the timeline is
        too short to fit even one full test window after one step.

    Raises:
        ValueError: if ``timeline`` is empty, or if ``test_span``/``step``
            are not strictly positive, or ``embargo`` is negative.
    """
    if not timeline:
        raise ValueError("timeline must be non-empty")
    if test_span <= timedelta(0):
        raise ValueError("test_span must be positive")
    if step <= timedelta(0):
        raise ValueError("step must be positive")
    if embargo < timedelta(0):
        raise ValueError("embargo must be non-negative")

    start = min(timeline)
    end = max(timeline)

    folds: List[Fold] = []
    k = 1
    while True:
        split = start + k * step
        test_end = split + test_span
        if test_end > end:
            break
        train_end = split - embargo
        folds.append(
            Fold(
                index=len(folds),
                train_start=start,
                split=split,
                embargo=embargo,
                train_end=train_end,
                test_start=split,
                test_end=test_end,
            )
        )
        k += 1

    return folds


# --- Ambiguity log -----------------------------------------------------
# 1. Fable Sec. 2.6 does not pin down where the *first* split point T_1
#    falls relative to timeline start, nor whether "1-day embargo between
#    train and test" shrinks train, delays test, or both. Resolved by
#    picking the reading that satisfies the task's own adversarial
#    invariant verbatim ("no train sample timestamp falls within
#    [T_i - embargo, T_i + test_span]"): embargo shrinks the train side
#    only; test starts exactly at T_i. First split = start + step so the
#    first fold's anchored train window is non-degenerate.
# 2. "stepping 2 months" is read as advancing T_i by a fixed calendar
#    `step` (caller-supplied timedelta), not as a fixed number of folds --
#    fold generation stops once a full test window no longer fits.
